### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jarojiang** [zeusees/HyperLPR#3]
你好，最近正在学习车牌识别的项目，刚好看到您的代码，就下下来试着跑了一下，结果报错了。因为正在学习，不是很懂，想请教一下您。
ValueError: Dimension (-1) must be in the range [0, 2), where 2 is the number of dimensions in the input. for 'metrics/acc/ArgMax' (op: 'ArgMax') with input shapes: [?,?], 
![2017-10-04 2](https://user-images.githubusercontent.com/30456372/31171141-4f4b3b5c-a931-11e7-85fc-b57c65359c21.png)

**Comment by brucexiaok** [comment]
你这个dimension是-1，有可能是数据没有读入或者没有加载之类的错误，你可以吧具体报错部分的代码发出来看一下
