### ISSUE TITLE
关于OSError: cannot open resource

### ISSUE THREAD

**Issue by Vivianwxf** [zeusees/HyperLPR#4]
运行upload.py报错，如图，百度没有找到答案，请问该怎么解决？

File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\PIL\ImageFont.py", line 143, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource

**Comment by szad670401** [comment]
尝试注释掉Pipline 224行的 ：                image =  drawRectBox(image,rect,res)
